OhInstagramBundle_callback:
    pattern: /instaphp/callback
    defaults: { _controller: OhInstagramBundle:Instagram:callback }
    
OhInstagramBundle_logout:
    pattern: /logout
    defaults: { _controller: OhInstagramBundle:Instagram:logout }
    
OhInstagramBundle_ajax_location_search:
    pattern: /ajax/locationSearch
    defaults: { _controller: OhInstagramBundle:Instagram:locationSearch, _format: json }